import { PAWBatch, ICLMember, CallingLead, Participant } from '@/types/paw';

export const INITIAL_BATCHES: PAWBatch[] = [
  {
    id: 'batch-01',
    name: 'PAW Offline Ahmedabad Batch #42',
    code: 'PAW-AHM-42',
    type: 'Offline',
    venueOrLink: 'ICL Foundation Center, Navrangpura, Ahmedabad',
    startDate: '2026-10-18',
    endDate: '2026-10-20',
    welcomeStartDate: '2026-10-11', // T-7 days
    pawHeadId: 'user-paw-head',
    status: 'Calling',
    totalTargetRegistrations: 100,
    createdAt: '2026-10-01',
  },
  {
    id: 'batch-02',
    name: 'PAW Online Interactive Batch #15',
    code: 'PAW-ONL-15',
    type: 'Online',
    venueOrLink: 'Zoom Interactive Room (Link will be emailed to registered participants)',
    startDate: '2026-11-05',
    endDate: '2026-11-08',
    welcomeStartDate: '2026-10-29',
    pawHeadId: 'user-paw-head',
    status: 'Draft',
    totalTargetRegistrations: 150,
    createdAt: '2026-10-03',
  },
];

export const INITIAL_MEMBERS: ICLMember[] = [
  // PAW Head
  {
    id: 'user-paw-head',
    name: 'Sanjay Patel',
    phone: '+91 98250 11223',
    email: 'sanjay.paw@icl.org',
    role: 'PAW_HEAD',
    team: 'LEADERSHIP',
    isAvailable: true,
  },
  // Calling Team Hierarchy
  {
    id: 'lead-head-call',
    name: 'Rajesh Shah',
    phone: '+91 98240 33445',
    email: 'rajesh.shah@icl.org',
    role: 'LEADER_HEAD',
    team: 'CALLING',
    isAvailable: true,
  },
  {
    id: 'leader-call-1',
    name: 'Manish Dave',
    phone: '+91 94260 55667',
    email: 'manish.dave@icl.org',
    role: 'LEADER',
    team: 'CALLING',
    parentLeaderId: 'lead-head-call',
    isAvailable: true,
  },
  {
    id: 'member-call-1',
    name: 'Kavita Joshi',
    phone: '+91 99090 12345',
    email: 'kavita.j@icl.org',
    role: 'CALLING_MEMBER',
    team: 'CALLING',
    callingCapacity: 25,
    parentLeaderId: 'leader-call-1',
    isAvailable: true,
  },
  {
    id: 'member-call-2',
    name: 'Parth Mehta',
    phone: '+91 98980 67890',
    email: 'parth.m@icl.org',
    role: 'CALLING_MEMBER',
    team: 'CALLING',
    callingCapacity: 15,
    parentLeaderId: 'leader-call-1',
    isAvailable: true,
  },
  {
    id: 'member-call-3',
    name: 'Priya Desai',
    phone: '+91 97270 99887',
    email: 'priya.d@icl.org',
    role: 'CALLING_MEMBER',
    team: 'CALLING',
    callingCapacity: 35,
    parentLeaderId: 'leader-call-1',
    isAvailable: true,
  },

  // Welcome & Follow-up Team Hierarchy (Single Unified Team)
  {
    id: 'lead-head-welcome',
    name: 'Neha Shah',
    phone: '+91 98790 44556',
    email: 'neha.shah@icl.org',
    role: 'LEADER_HEAD',
    team: 'WELCOME_FOLLOWUP',
    isAvailable: true,
  },
  {
    id: 'leader-welcome-1',
    name: 'Bhavesh Prajapati',
    phone: '+91 94280 22334',
    email: 'bhavesh.p@icl.org',
    role: 'LEADER',
    team: 'WELCOME_FOLLOWUP',
    parentLeaderId: 'lead-head-welcome',
    isAvailable: true,
  },
  {
    id: 'member-welcome-1',
    name: 'Anita Trivedi',
    phone: '+91 98255 66778',
    email: 'anita.t@icl.org',
    role: 'WELCOME_MEMBER',
    team: 'WELCOME_FOLLOWUP',
    parentLeaderId: 'leader-welcome-1',
    isAvailable: true,
  },
  {
    id: 'member-welcome-2',
    name: 'Hardik Parmar',
    phone: '+91 99740 88990',
    email: 'hardik.p@icl.org',
    role: 'WELCOME_MEMBER',
    team: 'WELCOME_FOLLOWUP',
    parentLeaderId: 'leader-welcome-1',
    isAvailable: true,
  },
  {
    id: 'member-welcome-3',
    name: 'Rinal Solanki',
    phone: '+91 97120 11223',
    email: 'rinal.s@icl.org',
    role: 'WELCOME_MEMBER',
    team: 'WELCOME_FOLLOWUP',
    parentLeaderId: 'leader-welcome-1',
    isAvailable: true,
  },
];

export const INITIAL_CALLING_LEADS: CallingLead[] = [
  {
    id: 'lead-101',
    pawBatchId: 'batch-01',
    fullName: 'Dharmesh Panchal',
    phone: '+91 98251 44556',
    city: 'Ahmedabad',
    assignedMemberId: 'member-call-1', // Kavita Joshi
    callStatus: 'INTERESTED',
    callLogs: [
      {
        id: 'cl-1',
        timestamp: '2026-10-04 11:30',
        status: 'INTERESTED',
        note: 'Gave a positive response. Understood fee and timings. Will complete registration by evening.',
        callbackDate: '2026-10-05 18:00',
      }
    ],
    nextFollowupDate: '2026-10-05',
  },
  {
    id: 'lead-102',
    pawBatchId: 'batch-01',
    fullName: 'Pooja Soni',
    phone: '+91 98791 22334',
    city: 'Gandhinagar',
    assignedMemberId: 'member-call-1',
    callStatus: 'CALLBACK_REQUESTED',
    callLogs: [
      {
        id: 'cl-2',
        timestamp: '2026-10-04 14:15',
        status: 'CALLBACK_REQUESTED',
        note: 'Was in an office meeting. Requested a callback around 7:00 PM.',
        callbackDate: '2026-10-05 19:00',
      }
    ],
    nextFollowupDate: '2026-10-05',
  },
  {
    id: 'lead-103',
    pawBatchId: 'batch-01',
    fullName: 'Jignesh Vyas',
    phone: '+91 94270 33441',
    city: 'Ahmedabad',
    assignedMemberId: 'member-call-2', // Parth Mehta
    callStatus: 'REGISTERED',
    callLogs: [
      {
        id: 'cl-3',
        timestamp: '2026-10-03 16:45',
        status: 'REGISTERED',
        note: 'Registration completed. Transferred and handed over to Welcome Team.',
      }
    ],
  },
  {
    id: 'lead-104',
    pawBatchId: 'batch-01',
    fullName: 'Bhavin Thakkar',
    phone: '+91 99099 55667',
    city: 'Vadodara',
    assignedMemberId: 'member-call-2',
    callStatus: 'NOT_REACHABLE',
    callLogs: [
      {
        id: 'cl-4',
        timestamp: '2026-10-04 10:00',
        status: 'NOT_REACHABLE',
        note: 'Phone was switched off. Retry in the afternoon.',
      }
    ],
    nextFollowupDate: '2026-10-05',
  },
  {
    id: 'lead-105',
    pawBatchId: 'batch-01',
    fullName: 'Alpa Patel',
    phone: '+91 97260 88991',
    city: 'Ahmedabad',
    assignedMemberId: 'member-call-3', // Priya Desai
    callStatus: 'PENDING',
    callLogs: [],
  },
  {
    id: 'lead-106',
    pawBatchId: 'batch-01',
    fullName: 'Sachin Shah',
    phone: '+91 98242 77665',
    city: 'Rajkot',
    assignedMemberId: 'member-call-3',
    callStatus: 'INTERESTED',
    callLogs: [
      {
        id: 'cl-5',
        timestamp: '2026-10-04 17:20',
        status: 'INTERESTED',
        note: 'Excited about the workshop. Sent brochure on WhatsApp.',
      }
    ],
  }
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'part-001',
    loginId: 'PAW-AHM-001',
    pawBatchId: 'batch-01',
    fullName: 'Jignesh Vyas',
    phone: '+91 94270 33441',
    whatsappNumber: '+91 94270 33441',
    preferredLanguage: 'en',
    city: 'Ahmedabad',
    registeredAt: '2026-10-03',
    registrationStatus: 'Confirmed',
    whatsappGroupJoined: true,
    assignedCallingMemberId: 'member-call-2', // Handed over from Parth Mehta
    assignedWelcomeIclMemberId: 'member-welcome-1', // Dedicated to Anita Trivedi
    welcomeCallStatus: 'Completed',
    welcomeChecklist: {
      verified: true,
      datesConfirmed: true,
      whatsappConfirmed: true,
      firstAssignmentGuided: true,
      techSupportProvided: true,
      doubtsCleared: true,
      attendanceConfirmed: true,
      remarks: 'Welcome call went great. Joined WhatsApp group and started the first assignment.',
    },
    firstAssignmentStatus: 'Report_Generated',
    personalityType: 'Analytical Influencer (Type A)',
    personalityReportUrl: '/reports/PAW-AHM-001.pdf',
    followups: [
      {
        id: 'f-1',
        date: '2026-10-04',
        sessionNumber: 1,
        attended: true,
        assignmentCompleted: true,
        supportRequired: 'None',
        iclRemark: 'Completed all 40 questions and reviewed report.',
        escalatedToLeader: false,
      }
    ],
  },
  {
    id: 'part-002',
    loginId: 'PAW-AHM-002',
    pawBatchId: 'batch-01',
    fullName: 'Minakshi Shah',
    phone: '+91 98254 99001',
    whatsappNumber: '+91 98254 99001',
    preferredLanguage: 'en',
    city: 'Gandhinagar',
    registeredAt: '2026-10-03',
    registrationStatus: 'Confirmed',
    whatsappGroupJoined: true,
    assignedCallingMemberId: 'member-call-1',
    assignedWelcomeIclMemberId: 'member-welcome-1', // Also assigned to Anita Trivedi
    welcomeCallStatus: 'Completed',
    welcomeChecklist: {
      verified: true,
      datesConfirmed: true,
      whatsappConfirmed: true,
      firstAssignmentGuided: true,
      techSupportProvided: true,
      doubtsCleared: true,
      attendanceConfirmed: true,
      remarks: 'Welcome call finished. Questionnaire in progress.',
    },
    firstAssignmentStatus: 'In_Progress',
    followups: [
      {
        id: 'f-2',
        date: '2026-10-04',
        sessionNumber: 1,
        attended: true,
        assignmentCompleted: false,
        supportRequired: 'Technical',
        iclRemark: 'Answered 20 questions. Will complete the rest tonight.',
        escalatedToLeader: false,
      }
    ],
  },
  {
    id: 'part-003',
    loginId: 'PAW-AHM-003',
    pawBatchId: 'batch-01',
    fullName: 'Rahul Sharma',
    phone: '+91 98981 77665',
    whatsappNumber: '+91 98981 77665',
    preferredLanguage: 'en',
    city: 'Ahmedabad',
    registeredAt: '2026-10-04',
    registrationStatus: 'Payment_Verified',
    whatsappGroupJoined: false,
    assignedCallingMemberId: 'member-call-3',
    assignedWelcomeIclMemberId: 'member-welcome-2', // Dedicated to Hardik Parmar
    welcomeCallStatus: 'Pending',
    welcomeChecklist: {
      verified: false,
      datesConfirmed: false,
      whatsappConfirmed: false,
      firstAssignmentGuided: false,
      techSupportProvided: false,
      doubtsCleared: false,
      attendanceConfirmed: false,
      remarks: 'Welcome call pending. Scheduled in T-7 window.',
    },
    firstAssignmentStatus: 'Not_Started',
    followups: [],
  },
  {
    id: 'part-004',
    loginId: 'PAW-AHM-004',
    pawBatchId: 'batch-01',
    fullName: 'Suresh Vaghela',
    phone: '+91 97123 44556',
    whatsappNumber: '+91 97123 44556',
    preferredLanguage: 'en',
    city: 'Ahmedabad',
    registeredAt: '2026-10-02',
    registrationStatus: 'Confirmed',
    whatsappGroupJoined: true,
    assignedCallingMemberId: 'member-call-1',
    assignedWelcomeIclMemberId: 'member-welcome-3', // Dedicated to Rinal Solanki
    welcomeCallStatus: 'Callback_Required',
    welcomeChecklist: {
      verified: true,
      datesConfirmed: true,
      whatsappConfirmed: true,
      firstAssignmentGuided: false,
      techSupportProvided: false,
      doubtsCleared: false,
      attendanceConfirmed: false,
      remarks: 'Picked up call but was in transit. Asked to call back on Oct 5.',
    },
    firstAssignmentStatus: 'Not_Started',
    followups: [
      {
        id: 'f-3',
        date: '2026-10-04',
        sessionNumber: 1,
        attended: false,
        assignmentCompleted: false,
        supportRequired: 'Other',
        iclRemark: 'Welcome call incomplete. Urgent follow-up needed.',
        escalatedToLeader: true,
      }
    ],
  },
  {
    id: 'part-005',
    loginId: 'PAW-AHM-005',
    pawBatchId: 'batch-01',
    fullName: 'Pratik Kulkarni',
    phone: '+91 94290 88776',
    whatsappNumber: '+91 94290 88776',
    preferredLanguage: 'en',
    city: 'Surat',
    registeredAt: '2026-10-04',
    registrationStatus: 'Confirmed',
    whatsappGroupJoined: true,
    assignedCallingMemberId: 'member-call-2',
    assignedWelcomeIclMemberId: 'member-welcome-2',
    welcomeCallStatus: 'Completed',
    welcomeChecklist: {
      verified: true,
      datesConfirmed: true,
      whatsappConfirmed: true,
      firstAssignmentGuided: true,
      techSupportProvided: true,
      doubtsCleared: true,
      attendanceConfirmed: true,
      remarks: 'Guided participant on answering the online questionnaire.',
    },
    firstAssignmentStatus: 'Basic_Completed',
    followups: [],
  }
];
